# Generated by Django 4.1.7 on 2023-02-25 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_customer_remove_dealer_email_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.dealer'),
            preserve_default=False,
        ),
    ]
