# Generated by Django 4.1.7 on 2023-02-22 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('dealer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=199)),
                ('password', models.CharField(max_length=199)),
                ('dealer', models.CharField(max_length=199)),
                ('address_line1', models.CharField(max_length=199)),
                ('address_line2', models.CharField(blank=True, max_length=199)),
                ('address_line3', models.CharField(blank=True, max_length=199)),
                ('location', models.URLField()),
                ('phone_number1', models.IntegerField()),
                ('phone_number2', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=199)),
                ('lname', models.CharField(max_length=199)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dealer')),
            ],
        ),
    ]
