# Generated by Django 4.1.7 on 2023-02-22 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='username',
        ),
        migrations.AddField(
            model_name='dealer',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
